name: Publish ca-certificates
on:
  push:
    branches: [ master ]
    paths:
      - 'linux/ca-certificates/**'
      - '.github/workflows/cacert-publish.yml'

permissions:
  contents: read

jobs:
  publish-ca-certificates:
    if: github.repository == 'adoptium/installer'
    name: "Publish ca-certificates"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./linux

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
        with:
          java-version: '17'
          java-package: jdk
          architecture: x64
          distribution: 'temurin'

      - name: Build
        run: |
          export _JAVA_OPTIONS="-Xmx4G"
          ./gradlew --parallel :ca-certificates:package --stacktrace

      - name: Check if deb file exists in Artifactory
        id: check-deb
        run: |
          FILE=$(ls ca-certificates/debian/build/ospackage/*.deb)
          CODE=$(curl -s -o /dev/null -w "%{http_code}\n" https://packages.adoptium.net/artifactory/deb/pool/main/a/adoptium-ca-certificates/$(basename ${FILE}))
          echo "status=$CODE" >> GITHUB_OUTPUT

      - name: Upload deb file to Artifactory
        if: steps.check-deb.outputs.status == '404'
        run: |
          debVersionList=("buster" "bullseye" "bionic" "focal" "jammy" "kinetic")
          for debVersion in "${debVersionList[@]}"; do
            distroList+="deb.distribution=${debVersion};"
          done
          FILE=$(ls ca-certificates/debian/build/ospackage/*.deb)
          curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} \
          -X PUT -T $FILE "https://packages.adoptium.net/artifactory/deb/pool/main/a/adoptium-ca-certificates/$(basename ${FILE});deb.architecture=all;deb.component=main;${distroList}"
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
