name: macOS
on:
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/pkgbuild.yml
      - pkgbuild/**
jobs:
  pkgbuild:
    strategy:
      matrix:
        architecture: [x64, aarch64]
    name: pkgbuild
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

    - name: Install dependencies
      run: brew install --cask packages

    - name: Setup environment variables
      uses: allenevans/set-env@c4f231179ef63887be707202a295d9cb1c687eb9 # v2.2.0
      with:
        MAJOR_VERSION: 17
        FULL_VERSION: 17.0.3_7
        TAG: jdk-17.0.3+7
        SUB_TAG: 17.0.3_7
        JVM: hotspot

    - name: Download prebuilt binaries
      run: |
        mkdir -p workspace/target/
        cd workspace/target/
        wget -q "https://github.com/adoptium/temurin${{ env.MAJOR_VERSION }}-binaries/releases/download/${{ env.TAG }}/OpenJDK${{ env.MAJOR_VERSION }}U-jdk_${{ matrix.architecture }}_mac_${{ env.JVM }}_${{ env.SUB_TAG }}.tar.gz"

    - name: Create Package
      run: |
        export WORKSPACE=$PWD
        bash pkgbuild/create-installer-mac.sh

    - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
      with:
        name: macOS_${{ matrix.architecture }}
        path: workspace/target/*.pkg
