name: Windows
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/wix.yml
      - wix/**
jobs:
  wix:
    strategy:
      matrix:
        jdk: [8, 11, 17]
        include:
        - jdk: 8
          ICEDTEA_WEB_VERSION: "icedtea-web-1.8.6"
          PRODUCT_MAJOR_VERSION: 8
          PRODUCT_MINOR_VERSION: 0
          PRODUCT_MAINTENANCE_VERSION: 362
          PRODUCT_PATCH_VERSION: 0
          PRODUCT_BUILD_NUMBER: "09"
          MSI_PRODUCT_VERSION: 8.0.362.9
          ARCH: x64
          TAG: jdk8u362-b09
          SUB_TAG: 8u362b09
          JVM: hotspot
        - jdk: 11
          ICEDTEA_WEB_VERSION: ""
          PRODUCT_MAJOR_VERSION: 11
          PRODUCT_MINOR_VERSION: 0
          PRODUCT_MAINTENANCE_VERSION: 18
          PRODUCT_PATCH_VERSION: 0
          PRODUCT_BUILD_NUMBER: 10
          MSI_PRODUCT_VERSION: 11.0.18.10
          ARCH: x64
          TAG: jdk-11.0.18+10
          SUB_TAG: 11.0.18_10
          JVM: hotspot
        - jdk: 17
          ICEDTEA_WEB_VERSION: ""
          PRODUCT_MAJOR_VERSION: 17
          PRODUCT_MINOR_VERSION: 0
          PRODUCT_MAINTENANCE_VERSION: 6
          PRODUCT_PATCH_VERSION: 0
          PRODUCT_BUILD_NUMBER: 10
          MSI_PRODUCT_VERSION: 17.0.6.10
          ARCH: x64
          TAG: jdk-17.0.6+10
          SUB_TAG: 17.0.6_10
          JVM: hotspot

    name: wix
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: Install dependencies
        run: |
          choco install --no-progress wget

      - name: Setup environment variables
        uses: allenevans/set-env@c4f231179ef63887be707202a295d9cb1c687eb9 # v2.2.0
        with:
          PRODUCT_MAJOR_VERSION: ${{ matrix.PRODUCT_MAJOR_VERSION }}
          PRODUCT_MINOR_VERSION: ${{ matrix.PRODUCT_MINOR_VERSION }}
          PRODUCT_MAINTENANCE_VERSION: ${{ matrix.PRODUCT_MAINTENANCE_VERSION }}
          PRODUCT_PATCH_VERSION: ${{ matrix.PRODUCT_PATCH_VERSION }}
          PRODUCT_BUILD_NUMBER: ${{ matrix.PRODUCT_BUILD_NUMBER }}
          MSI_PRODUCT_VERSION: ${{ matrix.MSI_PRODUCT_VERSION }}
          ARCH: ${{ matrix.ARCH }}
          JVM: ${{ matrix.JVM }}

      - name: Download IcedTea-Web
        run: |
          cd wix\SourceDir
          wget -q "https://github.com/AdoptOpenJDK/IcedTea-Web/releases/download/${{ matrix.ICEDTEA_WEB_VERSION }}/${{ matrix.ICEDTEA_WEB_VERSION }}.win.bin.zip"
          unzip icedtea-web-*.win.bin.zip
          rm icedtea-web-*.win.bin.zip
          Remove-Item 'icedtea-web-image\share\doc' -Recurse
        if: ${{ matrix.ICEDTEA_WEB_VERSION != '' }}

      - name: Download Prebuilt JDK/JRE
        run: |
          cd wix\SourceDir
          wget -q "https://github.com/adoptium/temurin${{ env.PRODUCT_MAJOR_VERSION }}-binaries/releases/download/${{ matrix.TAG }}/OpenJDK${{ env.PRODUCT_MAJOR_VERSION }}U-jdk_${{ env.ARCH }}_windows_${{ env.JVM }}_${{ matrix.SUB_TAG }}.zip"
          wget -q "https://github.com/adoptium/temurin${{ env.PRODUCT_MAJOR_VERSION }}-binaries/releases/download/${{ matrix.TAG }}/OpenJDK${{ env.PRODUCT_MAJOR_VERSION }}U-jre_${{ env.ARCH }}_windows_${{ env.JVM }}_${{ matrix.SUB_TAG }}.zip"
          ./CreateSourceFolder.AdoptOpenJDK.ps1

      - name: Create JDK Installer
        run: |
          cd wix
          set PRODUCT_CATEGORY=jdk
          call Build.OpenJDK_generic.cmd
        shell: cmd

      - name: Create JRE Installer
        run: |
          cd wix
          set PRODUCT_CATEGORY=jre
          call Build.OpenJDK_generic.cmd
        shell: cmd

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: windows
          path: wix/ReleaseDir/*.msi
