name: Windows
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/wix.yml
      - wix/**
jobs:
  wix:
    strategy:
      matrix:
        jdk: [8, 11]
        include:
        - jdk: 8
          ICEDTEA_WEB_VERSION: "icedtea-web-1.8.6"
          PRODUCT_MAJOR_VERSION: 8
          PRODUCT_MINOR_VERSION: 0
          PRODUCT_MAINTENANCE_VERSION: 265
          PRODUCT_PATCH_VERSION: 0
          PRODUCT_BUILD_NUMBER: "01"
          MSI_PRODUCT_VERSION: 8.0.265.1
          ARCH: x64
          TAG: jdk8u265-b01
          SUB_TAG: 8u265b01
          JVM: hotspot
        - jdk: 11
          ICEDTEA_WEB_VERSION: ""
          PRODUCT_MAJOR_VERSION: 11
          PRODUCT_MINOR_VERSION: 0
          PRODUCT_MAINTENANCE_VERSION: 9
          PRODUCT_PATCH_VERSION: 1
          PRODUCT_BUILD_NUMBER: 11
          MSI_PRODUCT_VERSION: 11.0.9.1
          ARCH: x64
          TAG: jdk-11.0.9+11.1
          SUB_TAG: 11.0.9_11
          JVM: hotspot

    name: wix
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Install dependencies
        run: |
          choco install --no-progress wget

      - name: Setup environment variables
        uses: allenevans/set-env@c4f231179ef63887be707202a295d9cb1c687eb9 # v2.2.0
        with:
          PRODUCT_MAJOR_VERSION: ${{ matrix.PRODUCT_MAJOR_VERSION }}
          PRODUCT_MINOR_VERSION: ${{ matrix.PRODUCT_MINOR_VERSION }}
          PRODUCT_MAINTENANCE_VERSION: ${{ matrix.PRODUCT_MAINTENANCE_VERSION }}
          PRODUCT_PATCH_VERSION: ${{ matrix.PRODUCT_PATCH_VERSION }}
          PRODUCT_BUILD_NUMBER: ${{ matrix.PRODUCT_BUILD_NUMBER }}
          MSI_PRODUCT_VERSION: ${{ matrix.MSI_PRODUCT_VERSION }}
          ARCH: ${{ matrix.ARCH }}
          JVM: ${{ matrix.JVM }}

      - name: Download IcedTea-Web
        run: |
          cd wix\SourceDir
          wget -q "https://github.com/AdoptOpenJDK/IcedTea-Web/releases/download/${{ matrix.ICEDTEA_WEB_VERSION }}/${{ matrix.ICEDTEA_WEB_VERSION }}.win.bin.zip"
          unzip icedtea-web-*.win.bin.zip
          rm icedtea-web-*.win.bin.zip
          Remove-Item 'icedtea-web-image\share\doc' -Recurse
        if: ${{ matrix.ICEDTEA_WEB_VERSION != '' }}

      - name: Download Prebuilt JDK/JRE
        run: |
          cd wix\SourceDir
          wget -q "https://github.com/AdoptOpenJDK/openjdk${{ env.PRODUCT_MAJOR_VERSION }}-binaries/releases/download/${{ matrix.TAG }}/OpenJDK${{ env.PRODUCT_MAJOR_VERSION }}U-jdk_${{ env.ARCH }}_windows_${{ env.JVM }}_${{ matrix.SUB_TAG }}.zip"
          wget -q "https://github.com/AdoptOpenJDK/openjdk${{ env.PRODUCT_MAJOR_VERSION }}-binaries/releases/download/${{ matrix.TAG }}/OpenJDK${{ env.PRODUCT_MAJOR_VERSION }}U-jre_${{ env.ARCH }}_windows_${{ env.JVM }}_${{ matrix.SUB_TAG }}.zip"
          ./CreateSourceFolder.AdoptOpenJDK.ps1

      - name: Create JDK Installer
        run: |
          cd wix
          set PRODUCT_CATEGORY=jdk
          call Build.OpenJDK_generic.cmd
        shell: cmd

      - name: Create JRE Installer
        run: |
          cd wix
          set PRODUCT_CATEGORY=jre
          call Build.OpenJDK_generic.cmd
        shell: cmd

      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with:
          name: windows
          path: wix/ReleaseDir/*.msi
